import { useEffect, useState } from 'react'
import { Link, Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom'
import { Activity, BookOpen, HeartPulse, LogOut, Menu, MessageCircle, NotebookPen, ShieldAlert, Wind, X } from 'lucide-react'
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import api from './api'
import { dailyAffirmation } from './affirmations'

const moods = [{ value: 'low', label: 'Low', score: 1 }, { value: 'uneasy', label: 'Uneasy', score: 2 }, { value: 'okay', label: 'Okay', score: 3 }, { value: 'good', label: 'Good', score: 4 }, { value: 'bright', label: 'Bright', score: 5 }]

function App() {
  const [user, setUser] = useState(null)
  const [checking, setChecking] = useState(true)
  useEffect(() => { api.get('/auth/me').then(({ data }) => setUser(data.user)).catch(() => {}).finally(() => setChecking(false)) }, [])
  if (checking) return <div className="center-state">Loading your space...</div>
  return <Routes><Route path="/login" element={user ? <Navigate to="/chat" /> : <AuthPage mode="login" onAuth={setUser} />} /><Route path="/register" element={user ? <Navigate to="/chat" /> : <AuthPage mode="register" onAuth={setUser} />} /><Route path="/resources" element={<ResourcesPage />} /><Route element={<Protected user={user} onLogout={() => setUser(null)} />}><Route path="/" element={<Navigate to="/chat" replace />} /><Route path="/chat" element={<ChatPage />} /><Route path="/mood" element={<MoodPage />} /><Route path="/journal" element={<JournalPage />} /><Route path="/breathing" element={<BreathingPage />} /></Route><Route path="*" element={<Navigate to={user ? '/chat' : '/login'} replace />} /></Routes>
}

function Protected({ user, onLogout }) {
  const [open, setOpen] = useState(false); const navigate = useNavigate()
  const logout = async () => { await api.post('/auth/logout').catch(() => {}); onLogout(); navigate('/login') }
  if (!user) return <Navigate to="/login" replace />
  const links = [{ to: '/chat', label: 'Talk to Kai', icon: MessageCircle }, { to: '/mood', label: 'Mood check-in', icon: Activity }, { to: '/journal', label: 'Private journal', icon: NotebookPen }, { to: '/breathing', label: 'Breathe', icon: Wind }, { to: '/resources', label: 'Resources', icon: ShieldAlert }]
  return <div className="app-shell"><header className="topbar"><Link className="brand" to="/chat"><span className="brand-mark">K</span><span>Kai</span></Link><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setOpen(!open)}>{open ? <X size={21} /> : <Menu size={21} />}</button><nav className={open ? 'nav open' : 'nav'}>{links.map(({ to, label, icon: Icon }) => <NavLink key={to} onClick={() => setOpen(false)} className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'} to={to}><Icon size={17} />{label}</NavLink>)}<button className="nav-link nav-logout" onClick={logout}><LogOut size={17} />Sign out</button></nav></header><main className="main-content"><Routes><Route path="/chat" element={<ChatPage />} /><Route path="/mood" element={<MoodPage />} /><Route path="/journal" element={<JournalPage />} /><Route path="/breathing" element={<BreathingPage />} /><Route path="/resources" element={<ResourcesPage />} /></Routes></main><footer>Private by design. Kai is a wellness companion, not a medical professional.</footer></div>
}

function AuthPage({ mode, onAuth }) {
  const navigate = useNavigate(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const register = mode === 'register'
  const submit = async (event) => { event.preventDefault(); setError(''); setLoading(true); try { const { data } = await api.post(`/auth/${register ? 'register' : 'login'}`, form); onAuth(data.user); navigate('/chat') } catch (err) { setError(err.response?.data?.message || 'We could not complete that request.') } finally { setLoading(false) } }
  return <div className="auth-layout"><section className="auth-intro"><div className="brand"><span className="brand-mark">K</span><span>Kai</span></div><p className="eyebrow">A quieter place to land</p><h1>Make room for what you feel.</h1><p>Kai offers a private, thoughtful space for reflection, gentle conversation, and everyday wellbeing.</p><Link className="text-link" to="/resources">Need urgent support? Visit resources</Link></section><form className="auth-card" onSubmit={submit}><p className="eyebrow">Your private space</p><h2>{register ? 'Create your account' : 'Welcome back'}</h2><p className="muted">{register ? 'Start with an email and a password.' : 'Continue your check-in when you are ready.'}</p><label>Email<input type="email" required autoComplete="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Password<input type="password" required minLength="8" autoComplete={register ? 'new-password' : 'current-password'} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label>{error && <div className="error-box" role="alert">{error}</div>}<button className="primary-button" disabled={loading}>{loading ? 'Please wait...' : register ? 'Create account' : 'Sign in'}</button><p className="switch-auth">{register ? 'Already have an account?' : 'New to Kai?'} <Link to={register ? '/login' : '/register'}>{register ? 'Sign in' : 'Create one'}</Link></p></form></div>
}

function Intro({ eyebrow, title, copy }) { return <div className="page-intro"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{copy && <p className="intro-copy">{copy}</p>}</div></div> }

function ChatPage() {
  const [messages, setMessages] = useState([]); const [text, setText] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState(''); const navigate = useNavigate()
  useEffect(() => { api.get('/chat/history').then(({ data }) => setMessages(data.messages)).catch(() => setError('Your conversation could not be loaded.')).finally(() => setLoading(false)) }, [])
  const send = async (event) => { event.preventDefault(); const message = text.trim(); if (!message || sending) return; setText(''); setError(''); const createdAt = new Date().toISOString(); setMessages((current) => [...current, { role: 'user', content: message, createdAt }, { role: 'assistant', content: '', createdAt }]); setSending(true); try { const response = await fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:5000/api'}/chat`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json', Accept: 'text/event-stream, application/json' }, body: JSON.stringify({ message }) }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.message || 'Kai is unavailable right now. Please try again.') } if (response.headers.get('content-type')?.includes('text/event-stream')) { const reader = response.body.getReader(); const decoder = new TextDecoder(); let reply = ''; while (true) { const { value, done } = await reader.read(); if (done) break; for (const line of decoder.decode(value, { stream: true }).split('\n')) { if (!line.startsWith('data: ')) continue; const eventData = JSON.parse(line.slice(6)); if (eventData.token) { reply += eventData.token; setMessages((current) => current.map((item, index) => index === current.length - 1 ? { ...item, content: reply } : item)) } if (eventData.done && eventData.message) { reply = eventData.message; setMessages((current) => current.map((item, index) => index === current.length - 1 ? { ...item, content: reply } : item)) } } } } else { const data = await response.json(); setMessages((current) => current.map((item, index) => index === current.length - 1 ? { ...item, content: data.message } : item)); if (data.crisis) navigate('/resources') } } catch (err) { setMessages((current) => current.slice(0, -1)); setError(err.message || 'Kai is unavailable right now. Please try again.') } finally { setSending(false) } }
  return <div className="page"><Intro eyebrow="Your check-in" title="Talk to Kai" copy="A private conversation for sorting through the day, one message at a time." /><section className="chat-panel"><div className="chat-messages" aria-live="polite">{loading ? <div className="empty-state">Loading your conversation...</div> : messages.length === 0 ? <div className="empty-state"><HeartPulse size={25} /><strong>Start wherever you are.</strong><span>Tell Kai what has been taking up space today.</span></div> : messages.map((message, index) => <div key={`${message.createdAt}-${index}`} className={`message-row ${message.role}`}><div className="message-bubble"><span>{message.content}</span><time>{new Date(message.createdAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</time></div></div>)}{sending && <div className="message-row assistant"><div className="message-bubble thinking">Kai is thinking...</div></div>}</div>{error && <div className="error-box chat-error" role="alert">{error}</div>}<form className="chat-form" onSubmit={send}><label className="sr-only" htmlFor="chat-message">Message Kai</label><textarea id="chat-message" value={text} onChange={(e) => setText(e.target.value)} placeholder="Write what is on your mind..." rows="2" disabled={sending} /><button className="primary-button" disabled={sending || !text.trim()}>Send</button></form></section></div>
}

function MoodPage() {
  const [entries, setEntries] = useState([]); const [selected, setSelected] = useState(''); const [note, setNote] = useState(''); const [days, setDays] = useState(7); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  const load = () => { setLoading(true); api.get(`/moods?days=${days}`).then(({ data }) => setEntries(data.moods)).catch(() => setMessage('Mood entries could not be loaded.')).finally(() => setLoading(false)) }; useEffect(load, [days])
  const submit = async (e) => { e.preventDefault(); if (!selected) return; try { await api.post('/moods', { mood: selected, note }); setMessage('Today’s check-in is saved.'); setNote(''); load() } catch { setMessage('That check-in could not be saved.') } }
  const chartData = [...entries].reverse().map((entry) => ({ date: entry.date.slice(5), score: moods.find((mood) => mood.value === entry.mood)?.score || 0 }))
  return <div className="page"><Intro eyebrow="Notice the pattern" title="Mood check-in" copy="A small daily pause can make patterns easier to see." /><div className="two-column"><form className="surface" onSubmit={submit}><h2>How are you feeling today?</h2><div className="mood-list">{moods.map((mood) => <button type="button" key={mood.value} className={selected === mood.value ? 'mood-option selected' : 'mood-option'} onClick={() => setSelected(mood.value)}><span className="mood-dot" />{mood.label}</button>)}</div><label>Optional note<textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="What is influencing your mood?" rows="4" /></label><button className="primary-button" disabled={!selected}>Save check-in</button>{message && <p className="form-message">{message}</p>}</form><section className="surface"><div className="section-heading"><div><h2>Your recent pattern</h2><p className="muted">A simple view of your last {days} days.</p></div><select value={days} onChange={(e) => setDays(e.target.value)} aria-label="Trend range"><option value="7">7 days</option><option value="30">30 days</option></select></div>{loading ? <div className="empty-state">Loading your mood history...</div> : entries.length === 0 ? <div className="empty-state">No check-ins yet. Your first one starts the pattern.</div> : <div className="mood-chart"><ResponsiveContainer width="100%" height={250}><BarChart data={chartData}><XAxis dataKey="date" stroke="#66808a" /><YAxis domain={[0, 5]} ticks={[1, 2, 3, 4, 5]} stroke="#66808a" /><Tooltip /><Bar dataKey="score" fill="#3c8c83" name="Mood" /></BarChart></ResponsiveContainer></div>}</section></div></div>
}

function JournalPage() {
  const [entries, setEntries] = useState([]); const [form, setForm] = useState({ title: '', content: '' }); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = () => { setLoading(true); api.get('/journal').then(({ data }) => setEntries(data.entries)).catch(() => setError('Your journal could not be loaded.')).finally(() => setLoading(false)) }; useEffect(load, [])
  const submit = async (e) => { e.preventDefault(); setError(''); try { if (editing) await api.put(`/journal/${editing}`, form); else await api.post('/journal', form); setForm({ title: '', content: '' }); setEditing(null); load() } catch (err) { setError(err.response?.data?.message || 'The entry could not be saved.') } }
  const remove = async (id) => { await api.delete(`/journal/${id}`); load() }
  return <div className="page"><Intro eyebrow="Put it into words" title="Private journal" copy="Your entries are only visible to your account." /><div className="two-column journal-layout"><form className="surface" onSubmit={submit}><h2>{editing ? 'Edit entry' : 'New entry'}</h2><label>Title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="A few words to name this moment" /></label><label>Entry<textarea required rows="10" value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} placeholder="Write freely. There is no perfect way to begin." /></label>{error && <div className="error-box">{error}</div>}<div className="button-row"><button className="primary-button">{editing ? 'Update entry' : 'Save entry'}</button>{editing && <button type="button" className="secondary-button" onClick={() => { setEditing(null); setForm({ title: '', content: '' }) }}>Cancel</button>}</div></form><section className="entry-list">{loading ? <div className="empty-state">Loading your entries...</div> : entries.length === 0 ? <div className="surface empty-state"><BookOpen size={25} /><strong>Your journal is quiet for now.</strong><span>When you are ready, begin with one honest sentence.</span></div> : entries.map((entry) => <article className="journal-entry" key={entry._id}><div className="section-heading"><div><h2>{entry.title}</h2><time>{new Date(entry.updatedAt).toLocaleDateString()}</time></div><div className="button-row"><button className="text-button" onClick={() => { setEditing(entry._id); setForm({ title: entry.title, content: entry.content }) }}>Edit</button><button className="text-button danger" onClick={() => remove(entry._id)}>Delete</button></div></div><p>{entry.content}</p></article>)}</section></div></div>
}

function BreathingPage() { const phases = ['Inhale', 'Hold', 'Exhale', 'Hold']; const [running, setRunning] = useState(false); const [seconds, setSeconds] = useState(4); const [phase, setPhase] = useState(0); useEffect(() => { if (!running) return undefined; const timer = setInterval(() => setSeconds((current) => { if (current <= 1) { setPhase((value) => (value + 1) % 4); return 4 } return current - 1 }), 1000); return () => clearInterval(timer) }, [running]); return <div className="page"><Intro eyebrow="Return to your breath" title="Box breathing" copy="Four steady counts can give your attention somewhere kind to rest." /><div className="wellness-grid"><section className="breathing-surface"><div className={`breath-box phase-${phase}`}><span>{phases[phase]}</span><strong>{seconds}</strong></div><p className="breath-instruction">{running ? `${phases[phase]} gently for ${seconds} seconds` : 'Begin when you feel ready'}</p><button className="primary-button" onClick={() => setRunning(!running)}>{running ? 'Pause practice' : 'Begin practice'}</button></section><section className="surface affirmation"><p className="eyebrow">For today</p><h2>{dailyAffirmation()}</h2><p className="muted">Keep this close as a gentle thought, not a task.</p></section></div></div> }

function ResourcesPage() { return <div className="page"><Intro eyebrow="Support beyond Kai" title="Resources" copy="If you may hurt yourself or are in immediate danger, contact local emergency services now and stay with someone you trust." /><div className="resource-list"><section className="resource-block urgent"><ShieldAlert size={22} /><div><h2>Immediate support</h2><p>Emergency services: <strong>[VERIFY LOCAL EMERGENCY NUMBER]</strong></p><p>Crisis helpline: <strong>[ADD VERIFIED CURRENT NUMBER]</strong></p><p>Text or chat support: <strong>[ADD VERIFIED CURRENT SERVICE]</strong></p></div></section><section className="resource-block"><BookOpen size={22} /><div><h2>Professional support</h2><p>A licensed counsellor, psychologist, psychiatrist, or doctor can help you find care that fits your situation.</p><p>College support office: <strong>[ADD YOUR INSTITUTION'S VERIFIED CONTACT]</strong></p></div></section><section className="resource-block"><HeartPulse size={22} /><div><h2>For the next few minutes</h2><p>Move near another person, put distance between yourself and anything you could use to hurt yourself, and tell someone clearly that you need company.</p></div></section></div></div> }

export default App
